### ISSUE TITLE
Http 404 not found for css and js files on first load

### ISSUE THREAD

**Issue by sceyhuns** [ligershark/WebOptimizer#100]
After publishing my .net core application it gives not found error for all css and js content on first time entering to site. Then it become ok after second load. How to resolve it?
![Annotation 2019-05-09 230532](https://user-images.githubusercontent.com/28824426/57480116-eba7d980-72af-11e9-93e2-3648a321863c.jpg)

**Comment by glaanc03** [comment]
We have teh same problem.
Any updates on this?

**Comment by nathankmiller** [comment]
I also just ran into this. Has anyone found a solution / explanation?

**Comment by nathankmiller** [comment]
Posting this in case it helps people work around / understand the issue.

I took a trace of an ASP.NET Core app being hosted in IIS where I was seeing the failures and figured out that writing the disk cache was failing on the first request:

![image](https://user-images.githubusercontent.com/1060640/103799933-9847da80-5000-11eb-9bf8-4412353456b1.png)

In my case I was able to turn off disk caching in `appsettings.json` to work around the issue.

**Comment by sceyhuns** [comment]
Sorry for late answer, this settings in 'appsettings.json' solved my problem:
```
  "webOptimizer": {
    "enableCaching": false,
    "enableTagHelperBundling": false
  }
```

**Comment by YanBrunet** [comment]
I had the same issue, at each new startup I had the same error where the bundle dowload was aborted.
It's not required to disable the whole caching, just disk caching:

`
    "webOptimizer": {
        "enableDiskCache": false
    }
`

**Comment by DaleCam** [comment]
shouldn't this be fixed instead of closed?
