### ISSUE TITLE
Bundle CSS file not created

### ISSUE THREAD

**Issue by matthewblott** [ligershark/WebOptimizer#108]
The css didn't appear to load and when I went to view the ```/css/bundle.css``` file I received the following error ...

```
TypeLoadException: Could not load type 'Microsoft.AspNetCore.Antiforgery.Internal.CryptographyAlgorithms' from assembly 'Microsoft.AspNetCore.Antiforgery, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
```

My setup is pretty vanilla - I copied what's on the homepage, here's my code.

```
services.AddWebOptimizer(pipeline =>
{
  pipeline.AddCssBundle("/dist/bundle.css", "css/**/*.css");
});

```

Any help appreciated :-)

**Comment by skimedic** [comment]
It looks like you have loaded the wrong version of the package loaded. If you are using .NET Core 2.x, use the 1.x version of web optimizer. If you are using .NET Core 3.x, use the 3.x version

**Comment by matthewblott** [comment]
Ah, I upgraded to 3.0 recently. Thanks for the swift response (sorry to have bothered you with something so trivial!).
