### ISSUE TITLE
Minify bundles only on production

### ISSUE THREAD

**Issue by georgeemr** [ligershark/WebOptimizer#133]
I have the following code:

```
services.AddWebOptimizer(_currentEnvironment,
                new CssBundlingSettings() { Minify = false },
                new CodeBundlingSettings() { Minify = false }, pipeline =>
                {
                    pipeline.AddCssBundle("/css/bundle.css",
                        "/vendor/animate/animate.css",
                        "/vendor/css-hamburgers/hamburgers.min.css",
                        "/vendor/bootstrap/css/bootstrap.min.css",
                        "/lib/jquery-confirm/jquery-confirm.min.css");

                    pipeline.AddJavaScriptBundle("/js/batsuinitdom.js",
                        "/lib/jquery/jquery.js",
                        "/lib/jquery-validate/jquery.validate.min.js",
                        "/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js",
                        "/lib/jquery-confirm/jquery-confirm.min.js",
                        "/vendor/animsition/js/animsition.min.js",
                       "/vendor/bootstrap/js/popper.js");                
                });
```

In my development environment, I need to avoid minifying the libraries. None of the options works. Is there a solution for this?

I was thinking this was the solution: new CssBundlingSettings() { Minify = false }

**Comment by skimedic** [comment]
This is in the readme:
Disabling minification:
If you want to disable minification (e.g. in development), the following overload for AddWebOptimizer() can be used:

if (env.IsDevelopment())
{
    services.AddWebOptimizer(minifyJavaScript:false,minifyCss:false);
}

**Comment by d-ziegler** [comment]
Disabling the minification does not work as said in the readme. The problem here is that the extension methods `AddCssBundle` and `AddJavascriptBundle` always call `MinifyCss`/`MinifyJavaScript` (see CssMinifier/JavaScriptMinifier -> AssetPipelineExtensions). 
Don't like that this gets done there though. For now I'm going to implement my own IAssetPipeline extension methods.

**Comment by georgeemr** [comment]
I will appreciate it if this gets fixed so the extension method respects the value. This is important as we can debug the code on development without the necessity of duplicate the code depending on the environment.

**Comment by georgeemr** [comment]
It's working now.
