### ISSUE TITLE
Globbing patterns with bundling always produces a path relative to current directory instead of the root.

### ISSUE THREAD

**Issue by mbriggs9374** [ligershark/WebOptimizer#136]
The following glob pattern produces a path relative to the current directory instead of the root.
pipeline.AddJavaScriptBundle("/bundles/scripts", "/Scripts/**/*.js") --> <script src="Scripts/subfolder1/file1.js"></script>

Expecting:
pipeline.AddJavaScriptBundle("/bundles/scripts", "/Scripts/**/*.js") --> <script src="/Scripts/subfolder1/file1.js"></script>

Manually adding each subfolder & file results in the expected results.

**Comment by mrdnote** [comment]
I can confirm that this bug is still an issue in the v3.0.311 of the nuget package.
