### ISSUE TITLE
Remove Responding from memory cache  messages form info log level

### ISSUE THREAD

**Issue by kobruleht** [ligershark/WebOptimizer#162]
ASP.NET 5 MVC application uses it in Debian linux.

syslog contains large number of information messages like

> Apr 18 09:12:26 c202-76 kestrel-store[28711]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: WebOptimizer.AssetMiddleware[1000]
> Apr 18 09:12:26 c202-76 kestrel-store[28711]:       Request started for '/css/siteerp.css'
> Apr 18 09:12:26 c202-76 kestrel-store[28711]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: WebOptimizer.AssetBuilder[1001]
> Apr 18 09:12:26 c202-76 kestrel-store[28711]:       Responding from memory cache for '/css/siteerp.css'
> Apr 18 09:12:26 c202-76 kestrel-store[28711]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: WebOptimizer.AssetMiddleware[1000]
> Apr 18 09:12:26 c202-76 kestrel-store[28711]:       Request started for '/lib/jquery/jquery.js'
> Apr 18 09:12:26 c202-76 kestrel-store[28711]: #033[40m#033[32minfo#033[39m#033[22m#033[49m: WebOptimizer.AssetBuilder[1001]
> 

How to disable those messages for WebOptimizer only to make log more compact? I havent found any documentation about log config.

Default appsettings.json is used:

```
{

  "AllowedHosts": "*",
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }

  }
}
```

**Comment by Hoai-Phong** [comment]
I still haven't fixed it, have you solved this problem yet? Please let me know with?

**Comment by kobruleht** [comment]
Solution is here: https://stackoverflow.com/questions/67145782/removing-responding-from-memory-cache-messages-form-info-log-level
