### ISSUE TITLE
Exclude file from minification

### ISSUE THREAD

**Issue by Reza-Babakhani** [ligershark/WebOptimizer#167]
How can I exclude a js file from minification?

**Comment by nikolayarhangelov-arnitek** [comment]
Using WebOptimizer with Blazor Server will throw an error when resolving `_framework/blazor.server.js`. It would be good to define a way to skip a particular file like _blazor.server.js_.

Configuration:
```
services.AddWebOptimizer()
app.UseWebOptimizer()
```

Error:
![image](https://user-images.githubusercontent.com/46623627/139855468-aee37a33-842e-4878-b2ab-45b5948b64cd.png)

**Comment by hhankj2u** [comment]
With blazor, you needn't disable minifyJavaScript.
You can use a globbing pattern to allow minification for all .js files in wwwroot, like below

`builder.Services.AddWebOptimizer(pipeline =>
{ 
    pipeline.MinifyJsFiles("js/**/*.js", "lib/**/*.js");  
});`

**Comment by nikolayarhangelov-arnitek** [comment]
Based on @hhankj2u's response I adjusted the globbing patter to use `pipeline.MinifyJsFiles("_content/**/*.js")` since the scripts are in Razor libraries.

**Comment by a-a-k** [comment]
@hhankj2u if I don't specify which files I wish to minify will they all become minified or no one?

**Comment by hhankj2u** [comment]
@a-a-k Just minify the files match your glob pattern. 
Please read the docs carefully. 
You can use debug to see which function will invoke in minify progress.
