### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by puhnastik** [ligershark/WebOptimizer#170]
We are observing memory leak in WebOptimizer code.  Memory usage graphs with WebOptimizer in place starting from 04/17 show significant increase in memory that doesn't get released and application eventually runs out of memory.
![image](https://user-images.githubusercontent.com/7429027/118799809-119ce700-b897-11eb-8739-777356157d9a.png)

I can reproduce the same issue on WebOptimizer [demo sample](https://github.com/ligershark/WebOptimizer/tree/master/sample)

Steps to reproduce:
1. Run [demo sample](https://github.com/ligershark/WebOptimizer/tree/master/sample) (any environment)
2. Open demo application in a browser and reload the page several times with browser cache disabled to ensure that static resources are requested on each page reload.
3. Create a memory dump for analysis or snapshot of memory profiler. I used dotMemory with configuration:
![image](https://user-images.githubusercontent.com/7429027/118810125-6a727c80-b8a3-11eb-9814-ea8ba70ccec8.png)
4. Analyze memory snapshot

The snapshot from dotMemory profiler shows increasing number of WebOptimizerConfig objects that don't get garbage collected. There is one new WebOptimizerConfig object get's created for each call to static content file.
![image](https://user-images.githubusercontent.com/7429027/118800227-9556d380-b897-11eb-8dfb-a7fff6da92da.png)

The issue seems to be in the ConfigurationReloadToken that doesn't get disposed (link to the code)[https://github.com/ligershark/WebOptimizer/blob/master/src/WebOptimizer.Core/WebOptimizerConfig.cs#L24]
![image](https://user-images.githubusercontent.com/7429027/118800823-3d6c9c80-b898-11eb-90a9-e8afe77e0956.png)
![image](https://user-images.githubusercontent.com/7429027/118801266-b9ff7b00-b898-11eb-859f-31195ebde5f9.png)

Attached dotMemory workspace for the demo sample
[WebOptimizer.Core.Sample.dmw.zip](https://github.com/ligershark/WebOptimizer/files/6508116/WebOptimizer.Core.Sample.dmw.zip)

**Comment by madskristensen** [comment]
Thank you so much for the best bug report I've ever received in my many years of doing OSS on GitHub!!!!

**Comment by mshiveral** [comment]
Thanks for picking this up and turning it around so quickly @madskristensen!
We plan on picking up the fix and verifying it in our DEV environment tomorrow.

Thanks!

**Comment by mshiveral** [comment]
Just confirming that the fix looks good in both our DEV and PERF environments @madskristensen.
Sorry for late reply (I was out for few days) and thanks for quick fix here!

**Comment by madskristensen** [comment]
@mshiveral awesome, thanks for the follow-up!!!
