### ISSUE TITLE
AddJavaScriptBundle and similar always minifies no matter the settings.

### ISSUE THREAD

**Issue by tamashburn** [ligershark/WebOptimizer#196]
I had to add my own extension methods that do not call .Minify<whatever>() after Concatenate(). I call them when CurrentEnvironment.IsDevelopment() is true. Looking at the source code, every overload of Add<something>Bundle has a Minify<whatever>() call. Yes, some have the settings argument, but that doesn't seem to matter.

This did not turn off minification: 

            services.AddWebOptimizer(
                CurrentEnvironment,
                new CssBundlingSettings { Minify = !CurrentEnvironment.IsDevelopment() },
                new CodeBundlingSettings { Minify = !CurrentEnvironment.IsDevelopment() }, // etc

        // My extensions
        public static IAsset AddJavaScriptBundleNoMinify(this IAssetPipeline pipeline, string route, params string[] sourceFiles)
        {
            return pipeline.AddBundle(route, "text/javascript; charset=UTF-8", sourceFiles)
                .EnforceFileExtensions(".js", ".jsx", ".es5", ".es6")
                .Concatenate()
                .AddResponseHeader("X-Content-Type-Options", "nosniff");
        }

        public static IAsset AddCssBundleNoMinify(this IAssetPipeline pipeline, string route, params string[] sourceFiles)
        {
            return pipeline.AddBundle(route, "text/css; charset=UTF-8", sourceFiles)
                .EnforceFileExtensions(".css")
                .AdjustRelativePaths()
                .Concatenate()
                .FingerprintUrls()
                .AddResponseHeader("X-Content-Type-Options", "nosniff");
        }

**Comment by Nouwan** [comment]
We have had a similar issue. We ended up using a work around by providing all AddJavaScriptBundle call's with the following codesettings object.
 
`CodeSettings codeSettings =
            new CodeSettings
            {
                MinifyCode = false,
                OutputMode = OutputMode.MultipleLines,
                ReorderScopeDeclarations = false
            };
`
  I have no clue if this is by design and the global level settings are only used for files automatically bundled from the wwroot folder, but it's either broken or confusing.

**Comment by a-milburn** [comment]
How can this be marked as Completed? this is a bug that needs to be fixed...
