### ISSUE TITLE
Minify on demand not working

### ISSUE THREAD

**Issue by christopherpickering** [ligershark/WebOptimizer#214]
Hi,

Thanks for the tool! 

#114 
#113 
@ctorx 

I am not able to get the "minify on demand" option working.
```html
<style minify>.nothing{background:pink}</style>
```

It looks like the app was updated, but possible that on-demand file left behind?

Changing this:
```c#
result = context.TagName.Equals("script", StringComparison.InvariantCultureIgnoreCase) 
                 ? Uglify.Js(input, ServiceExtensions.CodeBundlingSettings.CodeSettings) 
                 : Uglify.Css(input, ServiceExtensions.CssBundlingSettings.CssSettings);
```
to this
```c#
result = context.TagName.Equals("script", StringComparison.InvariantCultureIgnoreCase)
                ? Uglify.Js(input)
                : Uglify.Css(input);
```
seems to fix the problem. It looks like there is no longer a definition for `ServiceExtensions.Code...` and `ServiceExtensions.Css.`.

I ended up creating my own helper tag, that is identical to the minify one, but with these two lines changed.

**Comment by ctorx** [comment]
When you say not working, what do you mean?  

By the way I created the MinifyOnDemand in 2019 based on the state of the library at that time.  It is possible something internal has changed that's making it not work for you?

**Comment by christopherpickering** [comment]
Thanks for getting back so fast! Here's the error I get when try to run:

![image](https://user-images.githubusercontent.com/17788706/151258271-bd539fd0-a78e-492c-a006-bb7c580221ea.png)

Here's what I added in my _Layout:
```html
<style type="text/css" minify>body{color:red}</style>
```

And when I put the source in my own helper:

![image](https://user-images.githubusercontent.com/17788706/151258439-8a894843-39a6-436d-aab6-aaf655c53318.png)


But when I remove the `ServiceExtension..`, it runs fine. From the other help function files it looks like LigerShark may have changed how the settings work since this file was added.

**Comment by ctorx** [comment]
The ServiceExtension class that is exposing the AddWebOptimizer()
methods provides 3 different ways to set up WebOptimizer.

The variation that takes in both a CssBundlingSettings and a
CodeBundlingSettings as arguments is the version that must be used if you
want to make use of the Minify on demand tag helper.

That particular method is the only one of the three that instantiates
the CssBundlingSettings and CodeBundlingSettings on ServiceExtensions.

I would also suggest creating an issue that sets those values to defaults
in all other cases.

**Comment by christopherpickering** [comment]
Ah cool, do you happen to have a code snippet I can use for an example? Thanks!

**Comment by ctorx** [comment]
Check here, starting on line 29.

https://github.com/ligershark/WebOptimizer/blob/master/sample2/WebOptimizer.Core.Sample2/Startup.cs

**Comment by christopherpickering** [comment]
Thanks! That works great :)
