### ISSUE TITLE
Bundling without minification is not working

### ISSUE THREAD

**Issue by titiBeOne** [ligershark/WebOptimizer#247]
Hello,

I want to create bundle without minification for developpement (in order to have one configuration), and this code create bundle minified : 

```
builder.Services.AddWebOptimizer(builder.Environment, 
    new CssBundlingSettings { Minify = false}, 
    new CodeBundlingSettings { Minify = false }, 
    pipeline => pipeline.AddJavaScriptBundle("/js/bundle.js", "js/site.js", "js/site2.js")
    );
```

Is it possible create bundle unminified ?

**Comment by titiBeOne** [comment]
Ok I create this extensions methods to create bundle minified or not : 
A bundle Class :
`   public class Bundle
    {
        public string Route { get; set; }
        public string[] SourceFiles { get; set; }
    }`

And this extension method : 
`public static class WebOptimizerExtensions
    {
        public static void AddBundle(
          this IAssetPipeline pipeline,
          bool minify,
          IEnumerable<Bundle> bundles)
        {
            foreach (Bundle bundle in bundles)
            {
                pipeline.AddBundle(minify, bundle);
            }
        }

        public static IAsset AddBundle(
            this IAssetPipeline pipeline,
            bool minify,
            Bundle bundle)
        {
            return bundle.Route.ToLower().EndsWith(".css") ?
                pipeline.AddCssBundle(minify, bundle) :
                pipeline.AddJavaScriptBundle(minify, bundle);
        }

        public static IAsset AddCssBundle(
            this IAssetPipeline pipeline,
            bool minify,
            Bundle bundle)
        {
            return minify ? pipeline.AddCssBundle(bundle.Route, bundle.SourceFiles).UseContentRoot() :
                 pipeline.AddBundle(bundle.Route, "text/css; charset=UTF-8", bundle.SourceFiles)
                  .AdjustRelativePaths()
                  .AddSecurityToAsset(".css")
                  .FingerprintUrls();
        }


        public static IAsset AddJavaScriptBundle(
            this IAssetPipeline pipeline,
            bool minify,
             Bundle bundle)
        {
            return minify ? pipeline.AddJavaScriptBundle(bundle.Route, bundle.SourceFiles).UseContentRoot() :
               pipeline.AddBundle(bundle.Route, "text/javascript; charset=UTF-8", bundle.SourceFiles).
               AddSecurityToAsset(".js", ".jsx", ".es5", ".es6");
        }

        private static IAsset AddSecurityToAsset(this IAsset asset, params string[] extensions)
        {
            return asset.EnforceFileExtensions(extensions)
                 .Concatenate()
                 .AddResponseHeader("X-Content-Type-Options", "nosniff")
                 .UseContentRoot();
        }
    }`

To use like this in the startup :
`
        List<Bundle> bundles = new()
        {
            new Bundle{ Route =  "/js/lib1.js", SourceFiles = new string[] {    "Scripts/myfirstLib",
      "Scripts/libmySecondlib" } },
           new Bundle{ Route =   "/css/lib2.css",  SourceFiles = new string[] {    "Content/css/mythirdlib.css",
      "Content/css/myfourthlib.css"}
            }};

          services.AddWebOptimizer((assetPipeline) =>
            {
                assetPipeline.AddBundle(!CurrentEnvironment.IsDevelopment(), bundles);
            });
`

**Comment by dove** [comment]
Did this work for you?  I'm not getting any output at all.  I have a minimal program setup so perhaps need to tweak the order of setup.

**Comment by TechLiam** [comment]
The fix has now been released by the looks of things which is nice thought I'd mention it as I checked today to see if it had been

**Comment by titiBeOne** [comment]
Seems to work, but it would be great to have the same property for the css, 
for the css i have to work with OutputMode, SingleLine for the minify version MultipleLines for the unminified.

My code : 

        public static IAsset AddBundle(
            this IAssetPipeline pipeline,
            bool minify,
            Bundle bundle)
       {
           if (bundle.Route.ToLower().EndsWith(".css"))
            {
                CssSettings cssMinifySettings = new() 
                         {  
                           OutputMode = minify ? NUglify.OutputMode.SingleLine: NUglify.OutputMode.MultipleLines, 
                            CommentMode = minify ? CssComment.None : CssComment.All
                        };
                return pipeline.AddCssBundle(bundle.Route, cssMinifySettings, bundle.SourceFiles).UseContentRoot();
            }
            CodeSettings codeCodeSettings = new() 
            { 
                       MinifyCode = minify, 
                       PreserveImportantComments = minify 
             };
            return pipeline.AddJavaScriptBundle(bundle.Route, codeCodeSettings, bundle.SourceFiles).UseContentRoot();
        }
`

**Comment by TechLiam** [comment]
@prashanthbachu into which method are you passing codeSettings and which version of the package are you using?

**Comment by TechLiam** [comment]
So this works for me.

pipeline
            .AddJavaScriptBundle("/Scripts/app.js", new CodeSettings() { MinifyCode = false }, "/Scripts/main.js", "/Scripts/app/*.js")
            .UseContentRoot();

I'm doing UseContentRoot as my files are not in the wwwroot folder thing as I'm old school like that, but if your files are in the wwwroot folder you shouldn't need that.
