### ISSUE TITLE
Enable/Disable bundling based on preprocessor

### ISSUE THREAD

**Issue by ashu66867** [ligershark/WebOptimizer#288]
Is it possible to disable the bundling for DEBUG mode and enable it for RELEASE mode?

I am migrating a .Net framework project, which has the below:
          #if DEBUG
                      BundleTable.EnableOptimizations = false;
          #else
                      BundleTable.EnableOptimizations = true;
          #endif
                      }

Does WebOptimizer have any option or settings to do similar stuff?

**Comment by osjoberg** [comment]
Given that you configure `AddWebbOptimizer` with a pipeline and that you are using the included taghelpers to "render" the bundle just change `EnableTagHelperBundling` appropriately like this:

```` lang-cs
#if DEBUG
   var useWebOptimizer = false;
#else
   var useWebOptimizer = true;
#endif

services.AddWebOptimizer(
    pipeline =>
    {
       pipeline.AddJavaScriptBundle("/bundles/js","/scripts/a.js","/scripts/b.js");             
       pipeline.AddCssBundle("/bundles/css","/scripts/a.css","/scripts/b.css");
    },
    option =>
    {
       option.EnableCaching = true;
       option.EnableTagHelperBundling = useWebOptimizer;
    });
````
