### ISSUE TITLE
Using with .NET 8, when named site.js, file doesn't minify.

### ISSUE THREAD

**Issue by eaglei22** [ligershark/WebOptimizer#306]
I'm using .NET 8 as my target framework and for some reason when the javascript file is named site.js (the default file) it won't minify..  if I change the name though it works. 

site.css works fine however .

-wwwroot 
 -js
   -site.js

Version 3.0.405

**Comment by AderitoSilva** [comment]
That's odd. It works well for me with that same exact set up. Does that also happen if you try to create a new project and add WebOptimizer to it, or does it only happen in a specific project?

**Comment by eaglei22** [comment]
Okay, tried a new project with the same setup and js code, and it's working correctly.  

Weird, guess I should have done that in the first place. It didn't cross my mind because this project was just created a couple weeks ago. 

Anyway, thanks for verifying!
