### ISSUE TITLE
CSS/JS files not found for projects involving modular approach.

### ISSUE THREAD

**Issue by supernarwen** [ligershark/WebOptimizer#51]
I have a project involving modular approach like https://github.com/simplcommerce/SimplCommerce/tree/master/src

It works fine for assets linked to host project but breaks down for class library projects having custom css and js files. 

```
FileNotFoundException: No files found matching "/blog/js/blog-custom.js" exist in "C:\Users\Documents\Visual Studio 2017\Projects\test\Test.Web\wwwroot\"
WebOptimizer.Asset.ExpandGlobs(IAsset asset, IHostingEnvironment env)
```

Its searching every files at host project and not on modules copied through gulp!

Here's the code used to copy modules and assets files at run time.

 ```
 public static IApplicationBuilder UseCustomizedStaticFiles(this IApplicationBuilder app, IList<ModuleInfo> modules)
        {
            app.UseStaticFiles();

            // Serving static file for modules
            foreach (var module in modules)
            {
                var wwwrootDir = new DirectoryInfo(Path.Combine(module.Path, "wwwroot"));
                if (!wwwrootDir.Exists)
                {
                    continue;
                }

                app.UseStaticFiles(new StaticFileOptions
                {
                    FileProvider = new PhysicalFileProvider(wwwrootDir.FullName),
                    RequestPath = new PathString("/" + module.ShortName)
                });
            }
            return app;
        }
```

**Comment by madskristensen** [comment]
This is currently not supported. When registering assets on the pipeline your only choice in terms for modifying the IFileProvider is to use the `ContentRootProvider` using the `UseContentRoot()` method.

For this to work, we need to be able to pass in a custom file provider when we register the WebOptimizer service. 

In your case where you have multiple file providers (one for each module), we should combine them all into a CompositeFileProvider.

**Comment by supernarwen** [comment]
So I should provide CompositeFileProvider to pipeline while registering the web optimizer service.

**Comment by madskristensen** [comment]
I just added a pipeline method called `UseFileProvider(IFileProvider provider)`.

You can call it like this:

```c#
var provider = new Microsoft.Extensions.FileProviders.PhysicalFileProvider(@"C:\path\to\my\root\folder");
pipeline.AddJavaScriptBundle("/js/scripts.js", "a.js", "b.js")
        .UseFileProvider(provider);
```

**Comment by madskristensen** [comment]
I'm releasing an updated NuGet package now and it should be ready to use in about 15-30 minutes. Thanks for reporting this issue. Let me know if this works for you

**Comment by supernarwen** [comment]
Sure thank u very much.

**Comment by supernarwen** [comment]
Have u released it? I didn't find it!

**Comment by madskristensen** [comment]
Yes, it's version 1.0.177-beta https://www.nuget.org/packages/LigerShark.WebOptimizer.Core/1.0.177-beta
