### ISSUE TITLE
Is it possible to turn off all minification?

### ISSUE THREAD

**Issue by mog0** [ligershark/WebOptimizer#88]
I want to use your extension for bundling but I don't want any minification during development.
It seems to minify individual files that aren't in a bundle.
I tried putting in pipeline.MinifyJsFiles(""), hoping that it would ignore all files because the pattern didn't match, in the ConfigureServices but it throws an error saying it doesn't match any files.

I do however want to have minification in production so I don't want to put in code that can't easily be made conditional, e.g. like the suggestion for another question to do bundle("bundle", "fileshere").concatenate();

**Comment by skimedic** [comment]
I found that this works:
`            if (_env.IsDevelopment())
            {
                services.AddWebOptimizer(pipeline =>
                {
                    pipeline.MinifyCssFiles("foo.css");
                    pipeline.MinifyJsFiles("foo.js");
                });
            }
            else
            {
                services.AddWebOptimizer(pipeline =>
                {
                    pipeline.MinifyCssFiles("/css/**/*.css");
                    pipeline.MinifyJsFiles("/js/**/*.js");
                });
            }
`

**Comment by skimedic** [comment]
Ok, now that I am diving into the source code, simply use this code: `services.AddWebOptimizer(false,false);`

**Comment by skimedic** [comment]
This can be closed
