### ISSUE TITLE
ASP.NET Core 2.2: Exception because FileVersionProvider not available

### ISSUE THREAD

**Issue by saxx** [ligershark/WebOptimizer#94]
After I upgrade my ASP.NET Core 2.1 app to ASP.NET Core 2.2, I get this exception:

````
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLIQG41AEHKE", Request id "0HLIQG41AEHKE:00000001": An unhandled exception was thrown by the application.
System.TypeLoadException: Could not load type 'Microsoft.AspNetCore.Mvc.TagHelpers.Internal.FileVersionProvider' from assembly 'Microsoft.AspNetCore.Mvc.TagHelpers, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at WebOptimizer.Asset.GenerateCacheKey(HttpContext context)
   at WebOptimizer.AssetBuilder.BuildAsync(IAsset asset, HttpContext context, IWebOptimizerOptions options)
   at WebOptimizer.AssetMiddleware.HandleAssetAsync(HttpContext context, IAsset asset, WebOptimizerOptions options)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
````
It seems that the type `FileVersionProvider` is no longer available in 2.2 (or it has moved).

For now, I fixed it manually by forking WebOptimizer and simply removing the code that requires FileVersionProvider. I did not look into it further and what features I broke by removing these few lines of code (I think it has maybe something to do with caching?).

**Comment by brandtandreas** [comment]
I believe FileVersionProvider was renamed to DefaultFileVersionProvider and made internal in 2.2.

There is a registered service on the HttpContext.RequestServices which provides an IFileVersionProvider(DefaultFileVersionProvider I think).

I made this change #95, [fork](https://github.com/brandtandreas/WebOptimizer/tree/IFileVersionProvider), it won't work with ASP.NET Core versions below 2.2 though(might be a big problem).

**Comment by skimedic** [comment]
I created #97 to resolve the issue. I created a concrete FileVersionProvider. Works with 2.1 and 2.2 (didn't test 2.0 since it's out of support)

**Comment by skimedic** [comment]
I don’t have permissions to build the new package, so I just compiled from source and referenced the DLL directly for my 2.2 projects.

Regards,
 Phil

[cid:image003.png@01D3307E.D17B7D20]

Philip Japikse | Microsoft MVP, ASPInsider, MCSD, MCDBA, PSM II, PSD, CSM
Consultant, Coach, Author, Trainer
skimedic@outlook.com<mailto:skimedic@outlook.com> | c: 513.312.5664 | twitter: @skimedic<http://www.twitter.com/skimedic> | skype: phil.japikse
www.skimedic.com/blog<http://www.skimedic.com/blog> | Microsoft MVP<http://bit.ly/japikse-mvp> | Session Abstracts<http://tinyurl.com/skimedic-abstracts> | Lynda Courses<https://www.lynda.com/Phil-Japikse/7908546-1.html>

**Comment by ErcinDedeoglu** [comment]
Any news?

**Comment by skimedic** [comment]
This can be closed.
